version: '3'

services:
  realitica-app:
    image: 'romanew/realitica:latest'
    container_name: realitica
    network_mode: host
    environment:
      - server.port=10001
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/realitica
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - app.telegram.bot.token=${TELEGRAM_BOT_TOKEN}
      - management.endpoints.web.exposure.include=metrics,prometheus
    mem_limit: 512m
    restart: always