version: '3.7'

services:
  estate:
    image: 'romanew/estate:latest'
    container_name: estate
    network_mode: host
    environment:
      - server.port=10001
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/estate
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - app.telegram.bot.token=${TELEGRAM_BOT_TOKEN}
      - app.smtp.bot.host=${SMTP_HOST}
      - app.smtp.bot.port=${SMTP_PORT}
      - app.smtp.bot.login=${SMTP_LOGIN}
      - app.smtp.bot.password=${SMTP_PASSWORD}
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=60.0
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
