name: Java CI
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build jar
      run: ./gradlew bootJar

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: romanew/realitica:latest
        username: ${{ secrets.DOCKER_PUBLISH_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_PUBLISH_REGISTRY_PASSWORD }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy docker-compose-live.yml
      uses: garygrossgarten/github-action-scp@release
      with:
        local: docker-compose-live.yml
        remote: ./realitica/docker-compose-live.yml
        host: 193.17.92.2
        username: root
        privateKey: ${{ secrets.SSH_PRIVATE_KEY_ZTV }}

    - name: Start using docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: 193.17.92.2
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY_ZTV }}
        script: |
          cd realitica
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          docker-compose -f docker-compose-live.yml down
          docker-compose -f docker-compose-live.yml pull
          docker-compose -f docker-compose-live.yml up -d